export const STORE_PLAN_DETAILS = 'STORE_PLAN_DETAILS'
export const SET_ACTIVE_COURSE = 'SET_ACTIVE_COURSE'
export const SET_HOME_DROPPABLE = 'SET_HOME_DROPPABLE'
export const SET_SEARCH_WORD = 'SET_SEARCH_WORD'

export const SET_COURSELIST = 'SET_COURSELIST'
export const SET_COURSEPLAN = 'SET_COURSEPLAN'
export const SET_SELECTIONS = 'SET_SELECTIONS'

export const SET_AUTH_USER = 'SET_AUTH_USER'
export const SET_USER_PROFILE = 'SET_USER_PROFILE'
export const ADD_PLAN = 'ADD_PLAN'
export const DELETE_PLAN = 'DELETE_PLAN'
