const subjects = [
    "AERO ST",
    "ARCHEOL",
    "AF AMER",
    "ARCH&UD",
    "AFRC ST",
    "ARMENIA",
    "AFRKAAN",
    "ART",
    "AM IND",
    "ART HIS",
    "ASL",
    "ART&ARC",
    "AN N EA",
    "ARTS ED",
    "ANES",
    "ASIAN",
    "ANTHRO",
    "ASIA AM",
    "APPLING",
    "ASTR",
    "ARABIC",
    "A&O SCI",
    "BIOENGR",
    "BIOMATH",
    "BIOINFO",
    "BMD RES",
    "BIOINFR",
    "BIOSTAT",
    "BIOL CH",
    "BULGR",
    "C&EE ST",
    "COMM",
    "CH ENGR",
    "CESC",
    "CHEM",
    "COM HLT",
    "CHICANO",
    "COM LIT",
    "CHIN",
    "C&S BIO",
    "C&EE",
    "COM SCI",
    "CLASSIC",
    "CAEM",
    "CLUSTER",
    "CZCH",
    "DANCE",
    "DGT HUM",
    "DENT",
    "DIS STD",
    "DESMA",
    "DUTCH",
    "EPS SCI",
    "ENGL",
    "EA STDS",
    "ESL",
    "EE BIOL",
    "ENGCOMP",
    "ECON",
    "ENVIRON",
    "EDUC",
    "ENV HLT",
    "EC ENGR",
    "EPIDEM",
    "ENGR",
    "ETHNMUS",
    "FAM MED",
    "FOOD ST",
    "FILIPNO",
    "FRNCH",
    "FILM TV",
    "GENDER",
    "GJ STDS",
    "GEOG",
    "GLBL ST",
    "GERMAN",
    "GRAD PD",
    "GRNTLGY",
    "GREEK",
    "GLB HLT",
    "HLT POL",
    "HNRS",
    "HEBREW",
    "HUM GEN",
    "HIN-URD",
    "HNGAR",
    "HIST",
    "IL AMER",
    "INTL DV",
    "I E STD",
    "I M STD",
    "INDO",
    "IRANIAN",
    "INF STD",
    "ISLM ST",
    "I A STD",
    "ITALIAN",
    "JAPAN",
    "JEWISH",
    "KOREA",
    "LBR&WS",
    "UG-LAW",
    "LBR STD",
    "LGBTQS",
    "LATIN",
    "LIFESCI",
    "LATN AM",
    "LING",
    "LAW",
    "LTHUAN",
    "MGMT",
    "MED",
    "MGMTEX",
    "MIMG",
    "MGMTFT",
    "M E STD",
    "MGMTFE",
    "MIL SCI",
    "MGMTGEX",
    "M PHARM",
    "MGMTMFE",
    "MOL BIO",
    "MGMTMSA",
    "MOL TOX",
    "MGMTPHD",
    "MCD BIO",
    "MAT SCI",
    "MC&IP",
    "MATH",
    "MUSC",
    "MECH&AE",
    "MSC IND",
    "MED HIS",
    "MUSCLG",
    "NAV SCI",
    "NEUROSC",
    "NR EAST",
    "NEURO",
    "NEURBIO",
    "NEURSGY",
    "NEURLGY",
    "NURSING",
    "OBGYN",
    "ORL BIO",
    "OPTH",
    "ORTHPDC",
    "PATH",
    "POL SCI",
    "PEDS",
    "PORTGSE",
    "PHILOS",
    "COMPTNG",
    "PHYSICS",
    "PSYCTRY",
    "PBMED",
    "PSYCH",
    "PHYSCI",
    "PUB AFF",
    "PHYSIOL",
    "PUB HLT",
    "POLSH",
    "PUB PLC",
    "RAD ONC",
    "ROMANIA",
    "RELIGN",
    "RUSSN",
    "SCAND",
    "SOC GEN",
    "SCI EDU",
    "SOCIOL",
    "SEMITIC",
    "S ASIAN",
    "SRB CRO",
    "SEASIAN",
    "SLAVC",
    "SPAN",
    "SOC SC",
    "STATS",
    "SOC THT",
    "SURGERY",
    "SOC WLF",
    "SWAHILI",
    "THAI",
    "TURKIC",
    "THEATER",
    "UKRN",
    "URBN PL",
    "UNIV ST",
    "UROLOGY",
    "VIETMSE",
    "WL ARTS",
    "YIDDSH"
];

export default subjects;